MONEY = 400
BEST_SCORE = 10000

MONEY_PER_CLICK_COUNT = 0
POINTS_PER_CLICK_COUNT = 0
SECOND_LIFE_COUNT = 0
BOOST_COUNT = 0
AUTOPILOT_COUNT = 0
ENGINES_COUNT = 0
ROCKETS_COUNT = 0

MONEY_PER_CLICK_COST = 500
POINTS_PER_CLICK_COST = 1000
SECOND_LIFE_COST = 100
ROCKETS_COST = 100
ENGINES_COST = 500
BOOST_COST = 100
AUTOPILOT_COST = 100
ROCKETS_BEST_SCORE = 100

MONEY_PER_CLICK_COEF = 1.5
POINTS_PER_CLICK_COEF = 1.1
SECOND_LIFE_COEF = 1.2
BOOST_COEF = 1.2
AUTOPILOT_COEF = 1.2
ENGINES_COEF = 5
ROCKETS_COEF = 1.5

OPENED_ROCKETS = {0}
ROCKETS_SKIN_COUNT = 45

PLANETS_IDS = {}
BG_IMAGE_ID = ""

IS_SOUND = false
IS_PLAYING = false
IS_VIBRATION = false

BG_NUMBER = nil